// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4Fz8LikAStuQHygJ80VUxIUEvVGPQgkE',
    appId: '1:383989358861:web:c4920923d7a9f43bb3d044',
    messagingSenderId: '383989358861',
    projectId: 'qr-app-8f2fb',
    authDomain: 'qr-app-8f2fb.firebaseapp.com',
    storageBucket: 'qr-app-8f2fb.firebasestorage.app',
    measurementId: 'G-T0BDP8TGR2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjAkOCfbPKPs9jfo6r-sINEortUvG71qQ',
    appId: '1:383989358861:android:1d67530d9a3d265cb3d044',
    messagingSenderId: '383989358861',
    projectId: 'qr-app-8f2fb',
    storageBucket: 'qr-app-8f2fb.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAl9cVKmGtvJeC5MrCbB4GYLnyandu-8X4',
    appId: '1:383989358861:ios:6b72f2091798a778b3d044',
    messagingSenderId: '383989358861',
    projectId: 'qr-app-8f2fb',
    storageBucket: 'qr-app-8f2fb.firebasestorage.app',
    iosBundleId: 'com.example.qrLinkApp',
  );
}
